### PR TITLE
Version 2

### LINKED ISSUE #13: Allow injection of Enum/EnumValues

### LINKED ISSUE #30: CPP attendToInjectees leaks
Because ObjectMaps do not use weak references and CPP has no weakmap(https://github.com/HaxeFoundation/haxe/issues/3200) minject leaks for all objects injected or instantiated in CPP. I was able to verify this in GlowCode, a memory profiler for windows.

The ObjectMap is used in attendToInjectees. I'd prefer removing it altogether as I never run into the defensive use-case I think it was intended for. Or maybe you'd prefer a removal/exception for CPP? If you want removal for CPP only I have a branch ready.

### LINKED ISSUE #33: DCE eliminates injected stuff
One of the problems with using dependency injection is that the Haxe compiler likes to eliminate the constructors (and other parts) of injected classes, as most of them are never explicitly instantiated (created with `Type.createInstance` instead).

One possible macro based solution:

```
macro function mapClass(theClass:Expr)
function _mapClass(theClass:Class<Dynamic>);

// so, when you call mapClass it adds @:keep to theClass and generates
_mapClass(theClass);
```

The problem with this approach being that anyone calling the map methods (i.e. mmvc) need to do so in macro time too so that the types get through.

I'm open to better suggestions :)

### PR DESCRIPTION
**Pull request by dpeek**
Refactoring, cleanup, API improvements and all the other backwards incompatible things we want to do.

Public API is largely the same, but as some methods are now doing some macro magic a major version bump makes sense.

Main changes (so far):
- Fixes #30 removed attendedToInjectees
- Fixes #33 support DCE by marking injected types constructors with `@:keep`
- Fixes #13 support mapping any value type
- more compact RTTI metadata (adds up on large projects)
- general cleanup and refactoring to make API more consistent

Example RTTI before:
```
Foo.__meta__ = { fields : { a : { type : ["TypeA"], inject : null}, b : { type : ["TypeB"], inject : ["foo"]}, c : { type : ["TypeB"], inject : ["bar"]}}};
```

Example RTTI after:
```
Foo.__meta__ = { obj : { rtti : [["a","TypeA",""],["b","TypeB","foo"],["c","TypeB","bar"]]}};
```

### CODE REVIEW

**Comment by jasononeil** [comment]
I'll put some time into this tomorrow (Wed 14th Jan) to try it out with my various code bases and with ufront.  At a glance it looks great.

I want to road test `Injectormacro.getType`, and see if I've got any feedback there.  That's the change I'm most interested in... being able to inject Ints, Enums, Functions and Abstracts would make me pretty happy.

Thanks again, looking forward to v2 :)

**Comment by jasononeil** [comment]
Well, I never got to try this in January, my apologies.  Finally trying it out now, and I guess I'm doing something wrong because it feels pretty broken.

Here is a simple test file: https://gist.github.com/jasononeil/5672e1b36ec41dd596b1

Two problems:

1. When I run it like that, every non-class-instance (enums, ints, abstracts etc) just gives a null.
2. If I comment out all of the `mapValue()` calls in lines 7-10, the `getInstance()` call on line 14 does not throw an error - it silently fails to inject any data.

Anything I'm obviously doing wrong?

**Comment by thomasuster** [comment]
@dpeek Hey David, I'm happy to look into what @jasononeil posted. I'm a little hesitate since I spent a lot of time patching master branch with changes you decided to let go. If I can expect a timely merge I'll spend some time on this. Let me know.

**Comment by thomasuster** [comment]
Neko:
Uncaught exception - Invalid field access : _mapClass

Cpp:
parent changed to parentInjector (so I did find and replace)
Cannot access field or identifier parent for writing (parent is readonly)
Is your intent to switch all to createChildInjector?

**Comment by thomasuster** [comment]
bump

**Comment by dpeek** [comment]
Hi @jasononeil,

Sorry about this, a pretty simple fix but it took me a while to get round to it. Basically the roti was correct, but 'InjectorMacro.getType' was poorly written (or tested) and was returning completely the wrong string name for types when you used mapValue. This should work now, although it's likely there will be other edge cases that fail. At the moment `forType` needs to be a type in the local scope (so `Int`, `haxe.Http` and `foo.bar.Baz.Bing` should work). If you want to override it for some reason you can just call `mapTypeValue` with the type name you want (that's what gets called at runtime anyway).

@thomasuster I haven't looked at cpp yet, but the tests were passing in neko before this, so those errors look suspect...

**Comment by thomasuster** [comment]
@dpeek Is there a way to handle variable types with macros? See my branch below. 

https://github.com/thomasuster/minject/commit/17fc13e772828dd20f204527c0f7c7510a7ef61e

**Comment by dpeek** [comment]
@thomasuster what do you want to happen here? Inject `null` where `Class1` is requested?

**Comment by thomasuster** [comment]
@dpeek No, I just put null because it can be any argument like new Class1(). The fact that it's a variable holding the type doesn't allow this to compile in CPP. Tested on hxcpp 3.1.68.

**Comment by dpeek** [comment]
@thomasuster ah, ok. Well it's not supported at the moment, but it could be added. I'm not sure I understand the usefulness of it though... it's only going to work for types that are available at compile time, and normally my injector config happens far away from any actual instances...

**Comment by thomasuster** [comment]
@dpeek I use it for a few different things. One example is my own haxe implementation of signal command map. See https://github.com/joelhooks/signals-extensions-CommandSignal/blob/master/src/org/robotlegs/core/ISignalCommandMap.as

**Comment by dpeek** [comment]
@thomasuster but what do you want to map, compile time type or runtime type? Perhaps you should open another issue so we don't hijack this one :)

**Comment by thomasuster** [comment]
@dpeek I don't hijack issues. This is a PR to master, and master works with this use-case. Do you want me to open a separate issue?

**Comment by thomasuster** [comment]
Sounds good. I'll be chipping away at my problems here. https://github.com/massiveinteractive/minject/issues/37

**Comment by jasononeil** [comment]
If #51 is merged (or #49 fixed in some other manner) then I'm giving a :+1: to this.  Bring on the alpha/beta/whatever release on Haxelib.

**Pull request merged**
